### ISSUE TITLE
Tracing Center 

### ISSUE THREAD

**Issue by Chrisands** [Nexus-Mods/web-issues#217]
I got 11 mods, that i that and it shows them, but it's got second page and when i'm trying go on second page nothing happen. Why i got 2 pages, when i got only 11 mods in 20 mods page?

**Comment by Thallassa** [comment]
#69 but that was fixed.

**Comment by verenion** [comment]
Is this issue still happening, as I can't replicate this.

**Comment by Sereyon** [comment]
I do have the same bug. There are currently 303 mods in my Fallout4 tracking centre, so 15 full pages and 3 on page 16, but there is a total of 31 pages. Moving to these pages shows the 3 mods from page 16.

**Comment by KallumTanton** [comment]
I am still seeing this bug. For Skyrim SE I have 44 mods tracked, at 20 per page that's 3 pages but there are 5 pages available in the pagination. Likewise for Oldrim I have 66 tracked which is 5 pages but 9 are showing in the pagination.

As @Sereyon noted clicking on any of the extraneous pages returns results identical to the correct last page.

**Comment by alfx3** [comment]
Same problem, F4 Tracking Center, four pages, the last two being useless duplicates.

**Comment by iamtiz** [comment]
Assigned #153778713

**Comment by iamtiz** [comment]
fixed
