### ISSUE TITLE
Embedded YouTube videos too large

### ISSUE THREAD

**Issue by ousnius** [Nexus-Mods/web-issues#45]
With the redesign, embedded YouTube videos span across the whole horizontal body of a mod page, while on the old site they were a fixed size square.

A lot of people always put two videos next to each other, some even with multiple rows. Personally, I limit myself to two videos at the same time maximum, but while this was one row on the old site, it's two on the new.

Two videos in two rows, which used to be one (NSFW):
https://rd.nexusmods.com/fallout4/mods/15/

An even worse example, scroll down for a huge list of huge videos (NSFW):
https://rd.nexusmods.com/fallout4/mods/13572/

**Comment by mrmason** [comment]
The old design is fixed width. The new design can be anywhere from 1300px wide to 250px wide.

We've done 100% wide just because it's the easiest way to deal with that for now.

Any other suggestions are welcome.

**Comment by DuIslingr** [comment]
It should be left as is. Theres a videos tab for this very purpose. Limit one video allowed in the description. If you try and fit multiple on the same line for desktop, the result isnt likely to be as pretty for mobile.

**Comment by Thallassa** [comment]
I like the wide videos. I'm always frustrated trying to watch the little teeeny tiny videos on the old nexus. 

That said, videos belong in the video tab and changelogs belong in the changelog tab. If moderators were able to enforce this*, the vast majority of descriptions would look better. 

*(I know moderators can't enforce what they don't know about. There's a culture of not reporting things "because I didn't think it was a big deal" or "I didn't realize the moderators would do anything about it." That's SirSalami's problem, not the design team's problem).

**Comment by ousnius** [comment]
After some discussions in Discord, I agree it's not all that easy to have it work on desktop and mobile at the same time other than a width of 100% as it is now.

But I'm still not quite happy with how even one or two videos look on my page right now, maybe the width and height can be decreased by 50% after a certain resolution mode, so that I could still put two beside another on larger desktop resolutions?

Even reduced by 50% on bigger monitors, they're still twice as large as on the old site, so easily viewable.

**Comment by mrmason** [comment]
It might be possible for us to add in extra 'layouts' so that you have a choice on your size/positioning of media embedded in your descriptions at a later date

**Comment by Nazenn** [comment]
I would like something to be done about this as well, even if it is just a scaling option, or even just a click between small or large videos. 

I have videos in my description purely because users complain about wanting videos, but now I feel like I will have to take them out as it takes two whole page lengths to scroll past them to see anything else. Each video takes up my entire screen rather then just being a small addition in the description for those who want it. With mods that rely on videos to showcase their content because it just doesnt show properly in images or text, this is creating HUGE descriptions that are a pain to navigate.

**Comment by DuIslingr** [comment]
Again videos tab exists for a reason. Use it instead of wasting space with videos in the description. Especially now that the new site is responsive. On mobile its gonna look like crap even if you make desktop version prettier.

**Comment by mrmason** [comment]
Our long term goal is to replace the BBcode we currently have with rich HTML so that you'll be able to make layouts to your heart's content - although we will advise that this is going to cause issues with responsive layouts.

For now I think we're going to leave it as it is because we've got other problems that are more pressing to deal with - but we will look at this later.
